### ISSUE TITLE
Changing stages crashes the game

### ISSUE THREAD

**Issue by Cerrelle** [sourpuh/ffxiv_waymarkstudio#1]
Changing the stage (floor) in a fight seems to crash to desktop (ex. Sphene EX3, virtual shift),
Disabling Waymark Studio stops the crash

**Comment by Cerrelle** [comment]
It was constant last night, every time we hit first Virtual Shift to wind, the game crashed. As noted, disabling Waymark Studio stopped the crashing.

But, I don't know if it was just WS, or the fact that I had other plugins impacting waymarks as well (Waymark Preset Plugin and Memory Marker). But, I can send over the Dalamud crash log and dump file if that helps.

**Comment by sourpuh** [comment]
Yes please send me whatever you can

**Comment by Cerrelle** [comment]
Looks like the dump files are too big for git... I'll see if it will let me dm them to you.

**Comment by sourpuh** [comment]
I don't see evidence in the dump that this was caused by WMS. The crash stack trace is in occlusion culling which WMS does not call in any way that I'm aware of.
